### PR TITLE
Implementation of Metrics Framework

### PR DESCRIPTION
**Pull request by gkahiu**
Implements the metrics framework as described in #548.

### CODE REVIEW

**Review by Samweli — COMMENTED** [review]
@gkahiu Thanks for this. I'm getting the following errors when I run scenario with custom activity metrics.

image


Screenshot from 2024-12-05 15-35-21


image

**Comment by gkahiu** [comment]
Thanks @Samweli, I think I know where issue comes from. I'll push a fix. 

In the meantime, could you try with a numeric/non-string expression and let me know if there are any other issues encountered?

**Comment by amyburness** [comment]
@Samweli @gkahiu I tested this and all worked as expected. 

image

image

**Comment by gkahiu** [comment]
Thanks @amyburness for the feedback.

**Comment by Samweli** [comment]
@amyburness if everything is working as expected then we can merge and close this one, and put the remaining review into technical debt.

> @Samweli @gkahiu I tested this and all worked as expected. I am keen to see the automated expressions in the next PR
> 
> image
> 
> image

**Pull request merged**
