### PR TITLE
PWL Impact Calculation Metric

### PR DESCRIPTION
**Pull request by gkahiu**
This PR incorporates a metric for calculating the PWL impact of an activity. It provides an implementation for #576.

### CODE REVIEW

**Comment by amyburness** [comment]
@gkahiu Test there is an error as follows: 

image
image

**Comment by gkahiu** [comment]
@amyburness, most likely the area is zero for one or more activities. To confirm, could you:

1. Remove the 'pwl' column and try re-running the scenario;
2. After running the scenario, check if there are output activities under 'Weighted Activity Maps' legend group:

image

**Comment by amyburness** [comment]
@gkahiu 
there is an output and they activities appear in the output 
image

**Comment by amyburness** [comment]
@gkahiu 

I tested with a new clean project and a simple analysis and the PWL worked as expected. 
I am happy this is working

image

image
image

**Pull request merged**
