### PR TITLE
Irrecoverable Carbon Metric

### PR DESCRIPTION
**Pull request by gkahiu**
Implements #577 on the calculation of an activity's irrecoverable carbon based on its protected NCS pathways.

### CODE REVIEW

**Comment by amyburness** [comment]
I did make sure they where protect pathways 
image

**Comment by gkahiu** [comment]
Thanks @amyburness , did you specify the reference irrecoverable carbon dataset in the settings? You can use a local copy or download from the online server.

**Comment by amyburness** [comment]
ah @gkahiu I got it working with the settings set. 

Can you send me a few points on how to best use the online layer (I downloaded it, is that a mandatory step?)

image
image

**Comment by gkahiu** [comment]
Thanks @amyburness . A user will need to specify the reference IC dataset as we use this to fetch the mean carbon value per hectare for the calculation. The user has two options:
1. If they already have the reference dataset in their computer then they can select the Local option and point to this file.
2. Alternatively, they can also download the dataset from the online server. By default, we have preset the URL to the download API. All the user needs to do is specify the file path where the online file will be downloaded in the local computer. When the user clicks 'Start download', the system will try to retrieve the scenario extent (specified in Step 1) and append this to the API request sent to online server to clip the global dataset to this extent then initiate the download process for the clipped dataset to be saved locally. If the file already exists locally, it will be overwritten with the latest download as long as its not being used in the map canvas otherwise the user will have to specify a different file name. The download process is performed in the background (as a QGIS task) so if its a large download, depending on the AOI, the process will still continue uninterrupted even after the user closes the settings dialog. The progress will be shown as a percentage in QGIS' status bar with the final result logged, error or success, in the CPLUS log panel.

If the user has both options specified, i.e. a local option and an online version that had been downloaded locally, then they can choose which one to use simply by clicking on the corresponding radio button in the settings. E.g. if a user wants to use the local option for the calculation, then they simply click the local option and save the settings. Alternatively if i want to use the online version, then I select the online server radio button and save the settings. It will use the last selected radio button to determine which option to use in the calculation.

**Pull request merged**
